version: "3.9"
services:
  web:
    build: .
    ports:
      - "4000:4000"
  postgres:
      image: postgres
      container_name: 'postgres-data'
      environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_DB: 'postgres'
        PGDATA: /data/postgres
      volumes:
        - postgres:/data/postgres
      ports:
        - "5432:5432"
      networks:
        - postgres
      restart: unless-stopped