# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy nodejs

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout source code
          uses: actions/checkout@v2

        - name: Deploy elasticbeanstalk
          uses: hmanzur/actions-aws-eb@v1.0.0
          with:
            command: 'deploy --timeout 30'
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-east-1"
